[build]
builder = "DOCKERFILE"
dockerfilePath = "ops/source_backup/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 1200
restartPolicyType = "NEVER"
watchPatterns = ["/ops/source_backup/**"]
